//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotDrawer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class ControllerConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static ControllerConfig defaultInstance = ((ControllerConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ControllerConfig())));
        
        public static ControllerConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ABB.IRC5.OPC.Server.DA")]
        public string OPCServerName {
            get {
                return ((string)(this["OPCServerName"]));
            }
            set {
                this["OPCServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200-100530.RAPID.T_ROB1.OPCDraw.SetOfLines")]
        public string robotItemLinesArray {
            get {
                return ((string)(this["robotItemLinesArray"]));
            }
            set {
                this["robotItemLinesArray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200-100530.RAPID.T_ROB1.OPCDraw.nCountOfLines")]
        public string robotItemLinesToDrawCount {
            get {
                return ((string)(this["robotItemLinesToDrawCount"]));
            }
            set {
                this["robotItemLinesToDrawCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200-100530.RAPID.T_ROB1.OPCDraw.nCountOfCurrDrawLine")]
        public string robotItemCurrentlyDrawnLine {
            get {
                return ((string)(this["robotItemCurrentlyDrawnLine"]));
            }
            set {
                this["robotItemCurrentlyDrawnLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200-100530.RAPID.T_ROB1.OPCDraw.ReadyToDraw")]
        public string robotItemReadyToDraw {
            get {
                return ((string)(this["robotItemReadyToDraw"]));
            }
            set {
                this["robotItemReadyToDraw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200-100530.RAPID.T_ROB1.OPCDraw.Draw")]
        public string robotItemDraw {
            get {
                return ((string)(this["robotItemDraw"]));
            }
            set {
                this["robotItemDraw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200-100530.RAPID.T_ROB1.OPCDraw.ClearAll")]
        public string robotItemClearAll {
            get {
                return ((string)(this["robotItemClearAll"]));
            }
            set {
                this["robotItemClearAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200-100530.RAPID.T_ROB1.OPCDraw.ChangeTool")]
        public string robotItemChangeTool {
            get {
                return ((string)(this["robotItemChangeTool"]));
            }
            set {
                this["robotItemChangeTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360")]
        public string robotItemArraySize {
            get {
                return ((string)(this["robotItemArraySize"]));
            }
            set {
                this["robotItemArraySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200-100530.RAPID.T_ROB1.OPCDraw.xOffsetChangeColour")]
        public string robotItemToolOffsetArray {
            get {
                return ((string)(this["robotItemToolOffsetArray"]));
            }
            set {
                this["robotItemToolOffsetArray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200-100530.RAPID.T_ROB1.OPCDraw.GrabMarker")]
        public string robotItemGrabMarker {
            get {
                return ((string)(this["robotItemGrabMarker"]));
            }
            set {
                this["robotItemGrabMarker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200-100530.RAPID.T_ROB1.OPCDraw.GrabEraser")]
        public string robotItemGrabEraser {
            get {
                return ((string)(this["robotItemGrabEraser"]));
            }
            set {
                this["robotItemGrabEraser"] = value;
            }
        }
    }
}
